#ifndef _APP_DESTROYCOLOR_EVENTNAME_H_
#define _APP_DESTROYCOLOR_EVENTNAME_H_

// Gameplay
#define EVENT_MONSTER_CREATED "1"
#define EVENT_ROLE_CREATED "2"
#define EVENT_ROLE_DEAD "3"
#define EVENT_CAST_SKILL "4"
#define EVENT_MONSTER_CHANGEHP "5"
#define EVENT_MONSTER_CHANGECDTIME "6"
#define EVENT_MONSTER_FINISHED "7"
#define EVENT_MONSTER_DEAD "8"
#define EVENT_MONSTER_ATTACK "9"
#define EVENT_ROLE_CHANGEHP "10"
#define EVENT_SWAP_BLOCK "11"
#define EVENT_FIRST_EXPLODE "12"
#define EVENT_BATTLE_FINISH "13"

// UI
#define EVENT_UI_UPDATE_SEARCHPOINT "101"
#define EVENT_UI_UPDATE_GEM "102"
#define EVENT_UI_UPDATE_BAG "103"

// Skills
#define EVENT_SKILL_4_STARTED "201"
#define EVENT_SKILL_14_STARTED "202"

#endif